version: '3'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vote-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=vote
      - DB_USERNAME=vote
      - DB_PASSWORD=vote
    volumes:
      - ./backend:/var/www
    networks:
      - vote-network

  nginx:
    image: nginx:alpine
    container_name: vote-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - vote-network

  db:
    image: mysql:8.0
    container_name: vote-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=vote
      - MYSQL_ROOT_PASSWORD=vote
      - MYSQL_PASSWORD=vote
      - MYSQL_USER=vote
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - vote-network

networks:
  vote-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 